apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8080
      nodePort: 30443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: argocd-server